scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 0.49
    max_y: -0.31
    max_z: 3.0
    min_x: -0.49
    min_y: -0.31
    min_z: 0.0 
- type: laser_filters/LaserArrayFilter
  name: laser_median_filter
  params: 
    range_filter_chain:
      - name: median_3
        type: filters/MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 3
          unused: 0
    intensity_filter_chain:
      - name: median_3
        type: filters/MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 3
          unused: 0
#- name: shadows
#  type: laser_filters/ScanShadowsFilter
#  params:
#    min_angle: 10
#    max_angle: 170
#    neighbors: 20
#    window: 1
#- name: dark_shadows
#  type: laser_filters/LaserScanIntensityFilter
#  params: 
#    lower_threshold: 100
#    upper_threshold: 10000
#    disp_histogram: 0   