scan_filter_chain:
# radiusSearch filter remove isolated points
# neighbor number- neighbors to evaluate on EACH side
# threshold number- neighbors to have in order to be considered a valid point
# threshold radius- distance for considering nearby point
- name: srs_radius_search_filter
  type: laser_filters/RadiusSearchFilter
  params: 
    neighbor_number: 3
    threshold_number: 1
    threshold_ratio: 0.10 # ratio: search radius in meter per meter
- name: clean_up
  type: laser_filters/LaserScanRangeCleanUpFilter
