scan_filter_chain:
# box filter to filter out any point inside the root body
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_footprint
    max_x: 0.49
    max_y: 0.31
    max_z: 3.0
    min_x: -0.49
    min_y: -0.31
    min_z: 0.0
# median filter makes laser worse while the robot is moving
#- type: laser_filters/LaserArrayFilter
#  name: laser_median_filter
#  params: 
#    range_filter_chain:
#      - name: median_3
#        type: filters/MultiChannelMedianFilterFloat 
#        params:
#          number_of_observations: 11
#          unused: 0
#    intensity_filter_chain:
#      - name: median_3
#        type: filters/MultiChannelMedianFilterFloat 
#        params:
#          number_of_observations: 11
#          unused: 0
# scanShadow filter to filter out object shadow noise
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 2
    window: 1
# radiusSearch filter remove isolated points
# neighbor number- neighbors to evaluate on EACH side
# threshold number- neighbors to have in order to be considered a valid point
# threshold radius- distance for considering nearby point
- name: srs_radius_search_filter
  type: laser_filters/RadiusSearchFilter
  params: 
    neighbor_number: 15
    threshold_number: 2
    threshold_radius: 0.2
# intensity filter generally filters out only correct readings with low intensity 
#- name: dark_shadows
#  type: laser_filters/LaserScanIntensityFilter
#  params: 
#    lower_threshold: 50
#    upper_threshold: 10000
#    disp_histogram: 0   
