#
# (c) Copyright 2015-2016 River Systems, all rights reserved.
#
# This is proprietary software, unauthorized distribution is not permitted.
#

footprint: [[-0.5, -0.3], 
            [-0.5,  0.3], 
            [ 0.5,  0.3], 
            [ 0.5, -0.3]]
clearing_radius: 1.5   #0.59
footprint_padding: 0.1

controller_frequency: 10.0
controller_patience: 15.0

# base_global_planner: "global_planner/GlobalPlanner"
# base_local_planner: "dwa_local_planner/DWAPlannerROS"

#recovery_behavior_enabled: false

#planner_frequency: 0.0
#planner_patience: 60.0

#controller_frequency: 5.0
#controller_patience: 60.0

#shutdown_costmaps: false

#oscillation_distance: 1.0
#oscillation_timeout: 10.0







#controller_frequency: 10.0
#controller_patience: 3.0

#planner_frequency: 0.0
#planner_patience: 5.0

#recovery_behavior_enabled: false
#clearing_rotation_allowed: false

#shutdown_costmaps: false

#oscillation_timeout: 10.0
#oscillation_distance: 0.2

# local planner - default is trajectory rollout
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
