#
# (c) Copyright 2015-2016 River Systems, all rights reserved.
#
# This is proprietary software, unauthorized distribution is not permitted.
#

base_local_planner: "dwa_local_planner/DWAPlannerROS"

recovery_behavior_enabled: false

planner_frequency: 0.0
planner_patience: 5.0

controller_frequency: 10.0
controller_patience: 15.0

shutdown_costmaps: false

oscillation_distance: 0.5
oscillation_timeout: 10.0

# clearing_rotation_allowed: false
# controller_patience: 3.0

#oscillation_timeout: 10.0
#oscillation_distance: 0.2

