#
# (c) Copyright 2015-2016 River Systems, all rights reserved.
#
# This is proprietary software, unauthorized distribution is not permitted.
#



# Robot Configuration Parameters
acc_lim_x: 2.5
acc_lim_y: 2.5
acc_lim_th: 3.2
max_vel_x: 0.5
min_vel_x: 0.1
max_rotational_vel: 1.75
min_in_place_rotational_vel: 0.4
escape_vel: -0.1
holonomic_robot: false

# Goal Tolerance Parameters
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.05

# Forward Simulation Parameters
sim_time: 1.7
sim_granularity: 0.025
vx_samples: 3
vtheta_samples: 20

# Trajectory Scoring Parameters
goal_distance_bias: 0.8
path_distance_bias: 0.6
occdist_scale: 0.01
heading_lookahead: 1.325
dwa: true

# Oscillation Prevention Parameters
oscillation_reset_dist: 0.05

controller_frequency: 20.0
#planner_patience: 5.0
#controller_patience: 5.0

#TrajectoryPlannerROS:

#  max_vel_x: 0.2
#  min_vel_x: 0.05
#  max_rotational_vel: 1.0
#  min_in_place_rotational_vel: 0.2
#  escape_vel: -0.10
#  acc_lim_th: 0.8
#  acc_lim_x: 0.2
#  acc_lim_y: 0.2

#  holonomic_robot: false
#  yaw_goal_tolerance: 0.087 # about 5 degrees
#  xy_goal_tolerance: 0.05 # 5 cm
#  goal_distance_bias: 0.6
#  path_distance_bias: 0.8

##  heading_lookahead: 0.325
#  meter_scoring: true
#  heading_scoring: false
#  oscillation_reset_dist: 0.05
#  occdist_scale: 0.05
#  publish_cost_grid_pc: false

#  sim_time: 1.0
#  sim_granularity: 0.01
#  angular_sim_granularity: 0.01
#  vx_samples: 6
#  vtheta_samples: 20
#  dwa: false
#  
  
  