version: 2
jobs:
  build:
    docker:
      - image: 6river/rosbuild
    working_directory: /mfp_workspace
    environment:
      TEST_RESULTS: /Users/dan/src/ros/test_results/junit
    steps:
      - checkout
      - run:
          name: Run unit tests
          command:
            docker run --privileged -it ros-build-debian-armhf /bin/sh -c "catkin_make -j4 run_tests"
      - run:
          name: Save test results as junit format
          command:
            mkdir -p $TEST_RESULTS
            find /Users/dan/src/ros/build/test_results -type f -name '*.xml' -exec cp {} $TEST_RESULTS/ \;
      - store_artifacts:
          path: /Users/dan/src/ros/artifacts
          destination: raw-test-output
      - store_test_results:
          path: /Users/dan/src/ros/build/test_results
