global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 2.0
  publish_frequency: 0.1
  static_map: true
  rolling_window: false
  transform_tolerance: 0.5
  map_update_thread_affinity: 2
  static_layer:
    inflation:
        inflation_radius: 0.60
        cost_scaling_factor: 2.0
  obstruction_layer:
    inflation_radius: 0.6
  obstruction_layer_realsense:
    inflation_radius: 0.6
  plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayerWithInflation"}
   - {name: obstruction_layer, type: "costmap_2d::ObstructionLayer"}
   - {name: obstruction_layer_realsense, type: "costmap_2d::ObstructionLayer"}
