#
# (c) Copyright 2015-2016 River Systems, all rights reserved.
#
# This is proprietary software, unauthorized distribution is not permitted.
#

#Independent settings for the planner's costmap
global_costmap:
    publish_voxel_map: true
    global_frame: map
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 0.0
    static_map: true
    rolling_window: false
    obstacle_range: 2.5
    raytrace_range: 3.0


#global_costmap:
#    global_frame: /map
#    robot_base_frame: /base_footprint
#    update_frequency: 1.0
#    publish_frequency: 1.0
#    static_map: true
#    rolling_window: false


#global_costmap:
#  global_frame: /map
#  robot_base_frame: /base_footprint
#  update_frequency: 1.0
#  publish_frequency: 1.0
#  static_map: true
#  rolling_window: false
