function map = mm_addCustomBorder(map, x1, y1, x2, y2, envelope, costEnvelope)

    if nargin < 7
        costEnvelope = 255;
    end
    if nargin < 6
        envelope = 0.8;
    end
    
    % Top border
    map = mm_addStaticObstacle(map, ...
        0, 0, ...
        map.widthM, y1, ...
        envelope, costEnvelope);
    
    % Left border
    map = mm_addStaticObstacle(map, ...
        0, y1, ...
        x1, map.heightM, ...
        envelope, costEnvelope);
    
    % Top border
    map = mm_addStaticObstacle(map, ...
        x1, y2, ...
        map.widthM, map.heightM, ...
        envelope, costEnvelope);
    
    % Right border
    map = mm_addStaticObstacle(map, ...
        x2, y1, ...
        map.widthM, y2, ...
        envelope, costEnvelope);
end