function map = mm_addCustomBorder(map, x1, y1, x2, y2)

    % Top border
    map = mm_addStaticObstacle(map, ...
        0, 0, ...
        map.widthM, y1, ...
        0.5, 255);
    
    % Left border
    map = mm_addStaticObstacle(map, ...
        0, y1, ...
        x1, map.heightM, ...
        0.5, 255);
    
    % Top border
    map = mm_addStaticObstacle(map, ...
        x1, y2, ...
        map.widthM, map.heightM, ...
        0.5, 255);
    
    % Right border
    map = mm_addStaticObstacle(map, ...
        x2, y1, ...
        map.widthM, y2, ...
        0.5, 255);
end