function map = mm_addBorder(map, thickness)

    % Top border
    map = mm_addStaticObstacleRectangle(map, ...
        0, 0, ...
        map.widthM, thickness);
    
    % Bottom border
    map = mm_addStaticObstacle(map, ...
        0, map.heightM - thickness, ...
        map.widthM, map.heightM);
    
    % Left border
    map = mm_addStaticObstacle(map, ...
        0, 0, ...
        thickness, map.heightM);
    
    % Right border
    map = mm_addStaticObstacle(map, ...
        map.widthM - thickness, 0, ...
        map.widthM, map.heightM);
end