function map = mm_addOuterBorder(map, thickness, envelope, costEnvelope)

    if nargin < 4
        costEnvelope = 255;
    end
    if nargin < 3
        envelope = 0.8;
    end
    
    % Top border
    map = mm_addStaticObstacle(map, ...
        0, 0, ...
        map.widthM, thickness, ...
        envelope, costEnvelope);
    
    % Bottom border
    map = mm_addStaticObstacle(map, ...
        0, map.heightM - thickness, ...
        map.widthM, map.heightM, ...
        envelope, costEnvelope);
    
    % Left border
    map = mm_addStaticObstacle(map, ...
        0, 0, ...
        thickness, map.heightM, ...
        envelope, costEnvelope);
    
    % Right border
    map = mm_addStaticObstacle(map, ...
        map.widthM - thickness, 0, ...
        map.widthM, map.heightM, ...
        envelope, costEnvelope);
end