<?xml version="1.0"?>
<robot name="chuck" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find chuck_model)/urdf/properties.xacro"/>

	<xacro:include filename="$(find chuck_model)/urdf/common/inertia.xacro"/>
	<xacro:include filename="$(find chuck_model)/urdf/common/materials.xacro"/>
	
	<xacro:include filename="$(find chuck_model)/urdf/component/wheel.urdf.xacro"/>
	<xacro:include filename="$(find chuck_model)/urdf/component/caster.urdf.xacro"/>

	<!-- Robot footprint -->
	<link name="base_footprint">
	    <inertial>
	      <mass value="0.0001" />
	      <origin xyz="0 0 0" />
	      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
	          iyy="0.0001" iyz="0.0" 
	          izz="0.0001" />
	    </inertial>
	    <visual>
	        <origin xyz="0 0 0" rpy="0 0 0" />
	        <geometry>
	            <box size="0.001 0.001 0.001" />
	        </geometry>
	    </visual>
    </link>

	<gazebo reference="base_footprint">
		<turnGravityOff>false</turnGravityOff>
	</gazebo>
 
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="base_footprint"/>
		<child link="base_link"/>
	</joint>
 
	<!-- Chassis of the robot -->
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
			<material name="Blue"/>
		</visual>  

		<visual>
			<origin xyz="0 ${-support_distance / 2} ${support_zero}" rpy="0 0 0"/>
			<geometry>
				<box size="${support_x_size} ${support_y_size} ${support_z_size}"/>
			</geometry>
			<material name="Blue"/>
		</visual>

		<visual>
			<origin xyz="0 ${support_distance / 2} ${support_zero}" rpy="0 0 0"/>
			<geometry>
				<box size="${support_x_size} ${support_y_size} ${support_z_size}"/>
			</geometry>
			<material name="Blue"/>
		</visual>

		<visual>
			<origin xyz="0 0 ${tray_zero}" rpy="0 0 0"/>
			<geometry>
				<box size="${tray_x_size} ${tray_y_size} ${tray_z_size}"/>
			</geometry>
			<material name="Blue"/>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
		</collision>	 

		<inertial>
			<mass value="${base_mass}"/>
			<origin xyz="0 0 0"/>
			<box_inertia m="${base_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}"/> 
		</inertial>	
	</link>

	<!-- Wheels -->
	<wheel lr="left" parent="base_link" translateX="0" translateY="${-wheel_y_offset}" translateZ="0" />
	<wheel lr="right" parent="base_link" translateX="0"  translateY="${wheel_y_offset}" translateZ="0" />

	<!-- Castors -->
	<caster fb="front" parent="base_link" translateX="${caster_front_x_offset}" translateY="0" translateZ="${caster_z_offset}" />
	<caster fb="back" parent="base_link" translateX="${caster_back_x_offset}" translateY="0" translateZ="${caster_z_offset}" />

</robot>
