TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0

  acc_lim_theta: 2.0
  acc_lim_x: 2.5
  acc_lim_y: 0.0

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  
# Trajectory Scoring Parameters
  dwa: true  

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 1
