controller_frequency: 20.0
controller_patience: 15.0

planner_frequency: 0.0sdfd
planner_patience: 5.0

recovery_behavior_enabled: false
clearing_rotation_allowed: false

shutdown_costmaps: false

oscillation_timeout: 1.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"