# Obstacle cost shapping
footprint: [[-0.5,-0.3], [-0.5,0.3], [0.5, 0.3], [0.5,-0.3]]
resolution: 0.10000
inflation_radius: 1.0
cost_scaling_factor: 5.0
obstacle_range: 10.0
raytrace_range: 25.0

observation_sources: realsense

realsense: { sensor_frame: laser_frame, data_type: LaserScan, topic: /lidar/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3.0, expected_update_rate: 0.5 }