obstacles_laser:
  observation_sources: sick_lidar
  sick_lidar: {
    sensor_frame: sick_lidar,
    data_type: LaserScan,
    topic: /internal/sensors/lidar/scan/filtered,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 3.0,
    expected_update_rate: 0.25,
    inf_is_valid: true
  }

