# specify observation_sources for each layer
# two sensors will maintain marking and clearing separately in different layers
obstruction_layer:
  observation_sources: sick_lidar
  sick_lidar: {
    sensor_frame: sick_lidar,
    data_type: LaserScan,
    topic: /internal/sensors/lidar/scan/filtered,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 3.0,
    expected_update_rate: 0.25,
    inf_is_valid: true
  }

obstruction_layer_realsense:
 observation_sources: r200_rgbd
 r200_rgbd: {
   sensor_frame: camera_depth_frame,
   data_type: LaserScan,
   topic: /internal/sensors/rgbd/scan/filtered,
   marking: true,
   clearing: true,
   min_obstacle_height: 0.0,
   max_obstacle_height: 3.0,
   expected_update_rate: 0.25,
   inf_is_valid: true
 }



#############
## TO BE DELETED
#############
obstacle_layer:
  observation_sources: sick_lidar
  sick_lidar: {
    sensor_frame: sick_lidar,
    data_type: LaserScan,
    topic: /internal/sensors/lidar/scan/filtered,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 3.0,
    expected_update_rate: 0.25,
    inf_is_valid: true
  }

#obstacle_realsense_layer:
#  observation_sources: r200_rgbd
#  r200_rgbd: {
#    sensor_frame: camera_depth_frame,
#    data_type: LaserScan,
#    topic: /internal/sensors/rgbd/scan/filtered,
#    marking: true,
#    clearing: true,
#    min_obstacle_height: 0.0,
#    max_obstacle_height: 3.0,
#    expected_update_rate: 0.25,
#    inf_is_valid: true
#  }
