# Obstacle cost shapping
footprint: [[-0.5,-0.3], [-0.5,0.3], [0.5, 0.3], [0.5,-0.3]]
resolution: 0.10000
inflation_radius: 0.75
cost_scaling_factor: 2.0
obstacle_range: 3.5
raytrace_range: 4.0

transform_tolerance: 0.25

observation_sources: realsense

realsense: {
  sensor_frame: sick_lidar,
  data_type: LaserScan,
  topic: /internal/sensors/lidar/scan/filtered,
  marking: true,
  clearing: true,
  min_obstacle_height: 0.0,
  max_obstacle_height: 3.0,
  expected_update_rate: 0.25,
  inf_is_valid: true }