DWAPlannerROS:

  max_vel_x: 1.6
  min_vel_x: 0.1

  max_trans_vel: 0.65
  min_trans_vel: 0.1
  trans_stopped_vel: 0.1

  max_rot_vel: 0.65
  min_rot_vel: 0.1
  rot_stopped_vel: 0.65
  
  acc_lim_x: 0.65
  acc_lim_theta: 0.65
  acc_limit_trans: 0.65

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
#  sim_time: 1.7
#  sim_granularity: 0.025
#  vx_samples: 6
#  vtheta_samples: 20

# Trajectory Scoring Parameters
#  path_distance_bias: 64.0       # weighting for how much it should stick to the global path plan
#  goal_distance_bias: 24.0       # wighting for how much it should attempt to reach its goal
#  occdist_scale: 0.05           # weighting for how much the controller should avoid obstacles
#  forward_point_distance: 0.0   # how far along to place an additional scoring point
#  stop_time_buffer: 0.2         # amount of time a robot must stop in before colliding for a valid traj.
#  scaling_speed: 0.0            # absolute velocity at which to start scaling the robot's footprint
#  max_scaling_factor: 0.0       # how much to scale the robot's footprint when at speed.


# Oscillation Prevention Parameters
#  oscillation_reset_dist: 0.05  # how far to travel before resetting oscillation flags

# Debugging
#  publish_traj_pc : true
#  publish_cost_grid_pc: true

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 1
