global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 2.0
  publish_frequency: 0.1
  static_map: true
  rolling_window: false
  transform_tolerance: 0.5
  map_update_thread_affinity: 2
