global_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 2.0
  publish_frequency: 0.1
  static_map: true
  rolling_window: false
  transform_tolerance: 0.5
  map_update_thread_affinity: 2
  static_layer:
    inflation:
        inflation_radius: 0.75
  plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayerWithInflation"}
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: obstacle_realsense_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
