local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 15.0
  publish_frequency: 0.1
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  transform_tolerance: 0.5
  resolution: 0.05
  plugin:
  - {name: obstacles_laser, type: "costmap_2d::VoxelLayer"}
  - {name: obstacles_lidar, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
