local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5

#observation_sources: r200_rgbd sick_lidar
  observation_sources: sick_lidar

  sick_lidar: {
    sensor_frame: sick_lidar,
    data_type: LaserScan,
    topic: /internal/sensors/lidar/scan/filtered,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 3.0,
    expected_update_rate: 0.25,
    inf_is_valid: true
  }
  
  r200_rgbd: {
    sensor_frame: camera_depth_frame,
    data_type: LaserScan,
    topic: /camera/depth/scan,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 3.0,
    expected_update_rate: 0.25,
    inf_is_valid: true
  }