max_vel_x: 1.0
min_vel_x: 0.10

max_trans_vel: 1.0
min_trans_vel: 0.1
trans_stopped_vel: 0.005

max_rot_vel: 1.6
min_rot_vel: 0.5
rot_stopped_vel: 0.005

acc_lim_x: 0.7
acc_lim_theta: 2.5
acc_limit_trans: 0.7

# Goal Tolerance Parameters
yaw_goal_tolerance: 0.05
xy_goal_tolerance: 0.15
latch_xy_goal_tolerance: true

# Forward Simulation Parameters
sim_time: 1.7
sim_granularity: 0.1
angular_sim_granularity: 0.1
vx_samples: 14
vth_samples: 20
meter_scoring: true

# Trajectory Scoring Parameters
path_distance_bias: 2.0        # weighting for how much it should stick to the global path plan
goal_distance_bias: 1.0        # wighting for how much it should attempt to reach its goal
occdist_scale: 3.0           # weighting for how much the controller should avoid obstacles
velocity_scale: 0.75
forward_point_distance: 0.325 # how far along to place an additional scoring point
stop_time_buffer: 0.2         # amount of time a robot must stop in before colliding for a valid traj.
scaling_speed: 0.1          # absolute velocity at which to start scaling the robot's footprint
max_scaling_factor: 3.0       # how much to scale the robot's footprint when at speed.
cheat_factor: 25
jerk_scale: 0.1
# Oscillation Prevention Parameters
oscillation_reset_dist: 0.05  # how far to travel before resetting oscillation flags
oscillation_reset_angle: 1.6  # how far to turn before resetting oscillation flags
oscillation_reset_plan_divergence_distance: 0.3
# Debugging
publish_traj_pc: false
publish_cost_grid_pc: false

# Differential-drive robot configuration
holonomic_robot: false
max_vel_y: 0.0
min_vel_y: 0.0
acc_lim_y: 0.0
vy_samples: 0

# topics
#  odom_topic: /internal/sensors/odometry/velocity/estimate

use_dwa: false