local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 7.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  transform_tolerance: 0.5
