local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 15.0
  publish_frequency: 0.3
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  transform_tolerance: 0.5
  resolution: 0.05
  map_update_thread_affinity: 3
#  plugins:
#   - {name: static_layer, type: "costmap_2d::StaticLayer"}
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: obstacle_realsense_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # inflation_layer:
  #   inflation_radius: 1.0


  static_layer:
    inflation:
        inflation_radius: 0.75
        cost_scaling_factor: 2.0
  plugins:
#   - {name: static_layer, type: "costmap_2d::StaticLayer"}
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: static_layer, type: "costmap_2d::StaticLayerWithInflation"}
   - {name: obstruction_layer, type: "costmap_2d::ObstructionLayer"}
   - {name: obstruction_layer_realsense, type: "costmap_2d::ObstructionLayer"}
#   - {name: obstacle_realsense_layer, type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

