controller_frequency: 15.0
controller_patience: 1.0

planner_frequency: 1.0
planner_patience: 10.0

recovery_behavior_enabled: false
clearing_rotation_allowed: false

shutdown_costmaps: false

oscillation_timeout: 0.0
oscillation_distance: 0.5

conservative_reset_dist: 3.0

base_local_planner: "dwa_local_planner/DWAPlannerROS"
