controller_frequency: 3.0
controller_patience: 5.0

planner_frequency: 3.0
planner_patience: 5.0

recovery_behavior_enabled: true
#clearing_rotation_allowed: true

shutdown_costmaps: false

#oscillation_timeout: 10.0
#oscillation_distance: 0.2

#conservative_reset_dist: 0.2

# local planner - default is trajectory rollout
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
#base_local_planner: "eband_local_planner/EBandPlannerROS"