controller_frequency: 4.0
controller_patience: 15.0

planner_frequency: 2.0
planner_patience: 5.0

recovery_behavior_enabled: true
clearing_rotation_allowed: false

shutdown_costmaps: false

oscillation_timeout: 0.0
oscillation_distance: 0.5

conservative_reset_dist: 3.0

base_local_planner: "dwa_local_planner/DWAPlannerROS"