<?xml version="1.0"?>
<robot name="chuck" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- All units in m-kg-s-radians unit system -->
    <xacro:property name="M_PI" value="3.1415926535897931" />
    <xacro:property name="M_PI_2" value="1.570796327" />
    <xacro:property name="DEG_TO_RAD" value="0.017453293" />

    <!-- Chassis -->
    <xacro:property name="base_x_size" value="0.9772396" />
    <xacro:property name="base_y_size" value="0.619125" />
    <xacro:property name="base_z_size" value="0.3010916" />
    <xacro:property name="base_z_offset" value="0.01905" />
    <xacro:property name="base_mass" value="86.1826" />

	<xacro:property name="base_footprint_z_offset" value="${base_z_offset + base_z_size/2}" />

    <!-- Tray support -->
    <xacro:property name="support_x_size" value="0.050" />
    <xacro:property name="support_y_size" value="0.050" />
    <xacro:property name="support_z_size" value="0.600" />
    <xacro:property name="support_distance" value="0.254" />

    <xacro:property name="tray_x_size" value="0.863" />
    <xacro:property name="tray_y_size" value="0.635" />
    <xacro:property name="tray_z_size" value="0.038" />

    <xacro:property name="screen_x_size" value="0.020" />
    <xacro:property name="screen_y_size" value="0.300" />
    <xacro:property name="screen_z_size" value="0.200" />
    <xacro:property name="screen_inclination" value="0.200" />
    <xacro:property name="screen_mass" value="0.500" />

    <xacro:property name="body_zero" value="0" />
    <xacro:property name="support_zero" value="${body_zero + base_z_size / 2 + support_z_size / 2}" />
    <xacro:property name="tray_zero" value="${support_zero + support_z_size / 2 + tray_z_size / 2}" />

    <!-- Wheels -->
    <xacro:property name="wheel_radius" value="0.1016" />
    <xacro:property name="wheel_thickness" value="0.047625" />
    <xacro:property name="wheel_mass" value="2.118276" />
    <xacro:property name="wheel_y_offset" value="0.2661285" />
    <xacro:property name="wheel_z_offset" value="${-base_z_size/2 + wheel_radius - base_z_offset}" />

    <xacro:property name="caster_radius" value="0.0762" />
    <xacro:property name="caster_thickness" value="0.053975" />
    <xacro:property name="caster_mass" value="0.453592" />

    <xacro:property name="caster_x_size" value="0.1" />
    <xacro:property name="caster_y_size" value="0.1" />
    <xacro:property name="caster_z_size" value="0.2" />

    <xacro:property name="caster_front_x_offset" value="0.2885948" />
    <xacro:property name="caster_back_x_offset" value="-0.3564382" />
    <xacro:property name="caster_z_offset" value="${wheel_z_offset - (wheel_radius - caster_radius) + 0.0001 }" />

    <!-- Realsense Position (relative to base_link) -->
    <xacro:property name="r200_x_offset" value="${base_x_size/2}" />
    <xacro:property name="r200_y_offset" value="${r200_cam_y_size/2}" />
    <xacro:property name="r200_z_offset" value="${r200_cam_z_size + realsense_z_offset}" />

    <!-- Sensors -->

    <!-- Realsense -->
    <xacro:property name="realsense_z_rotation" value="${M_PI}" />
    <xacro:property name="realsense_z_offset" value="0.0641858" />

    <!-- SICK Lidar -->
    <xacro:property name="lidar_x_offset" value="0.4600448" />
    <xacro:property name="lidar_z_offset" value="0.3175" />
    <xacro:property name="lidar_rotation" value="${M_PI}" />

</robot>
