#
# (c) Copyright 2015-2016 River Systems, all rights reserved.
#
# This is proprietary software, unauthorized distribution is not permitted.
#

# Light Ids
uint32 TOTE_0 = 0
uint32 TOTE_1 = 1
uint32 TOTE_2 = 2
uint32 TOTE_3 = 3
uint32 TOTE_4 = 4
uint32 TOTE_5 = 5
uint32 TOTE_6 = 6
uint32 TOTE_7 = 7
uint32 ACTION = 100
uint32 PAUSE = 101
uint32 TAIL_LEFT = 201
uint32 TAIL_RIGHT = 202

# Light Modes
uint32 OFF = 0
uint32 ON = 1
uint32 ESTOP = 2
uint32 GRAB = 10
uint32 PUT = 11
uint32 BRAKE = 100
uint32 TURN = 101
uint32 SELECT = 102

# Light id
uint32 id

# Light mode
uint32 mode