<?xml version="1.0"?>
<robot name="stargazer" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Following values measured on the 3d model -->
  <xacro:property name="stargazer_x_size" value="0.064" />
  <xacro:property name="stargazer_y_size" value="0.058" />
  <xacro:property name="stargazer_z_size" value="0.053" />

  <xacro:property name="stargazer_optical_x_offset" value="-0.14" />
  <xacro:property name="stargazer_optical_y_offset" value="${stargazer_y_size/2}" />
  <xacro:property name="stargazer_optical_z_offset" value="${stargazer_z_size}" />

  <xacro:macro name="stargazer" params="parent translateX translateY translateZ">
 
    <joint name="stargazer_joint" type="fixed">
      <parent link="${parent}" />
      <child link="stargazer_link" />
      <origin xyz="${translateX} ${translateY} ${translateZ}" rpy="0 0 0" />
    </joint>
    
    <link name="stargazer_link">
      <visual>
        <origin xyz="${stargazer_x_size/2} ${-stargazer_y_size/2} ${stargazer_z_size/2}" rpy="0 0 0" />
        <geometry>
          <box size="${stargazer_x_size} ${stargazer_y_size} ${stargazer_z_size}" />
        </geometry>
        <material name="Gray" />
      </visual>
    </link>

    <joint name="stargazer_optical_joint" type="fixed">
      <parent link="stargazer_link" />
      <child link="stargazer_optical_frame" />
      <origin xyz="${stargazer_optical_x_offset + stargazer_x_size/2} ${-stargazer_y_size/2} ${stargazer_z_size}" rpy="0 0 0" />
    </joint>
    
	<link name="stargazer_optical_frame">
  	  <visual>
       <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
         <sphere radius="0.005"/>
        </geometry>
        <material name="green">
          <color rgba="0 0 1 1"/>
        </material>
      </visual>
    </link>

  </xacro:macro>
</robot>
