<?xml version="1.0"?>
<robot name="chuck" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="properties.xacro" />

    <xacro:include filename="common/inertia.xacro" />
    <xacro:include filename="common/materials.xacro" />
    
    <xacro:include filename="component/wheel.urdf.xacro" />
    <xacro:include filename="component/caster.urdf.xacro" />

	<xacro:include filename="sensors/r200.urdf.xacro"/>
	<xacro:include filename="sensors/stargazer.urdf.xacro"/>
	<xacro:include filename="$(find sick_tim)/urdf/sick_tim.urdf.xacro" />

    <!-- Robot footprint -->
    <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>
 
     <gazebo reference="base_footprint">
        <material>Gazebo/Blue</material>
        <turnGravityOff>false</turnGravityOff>
      </gazebo>
 
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_footprint_z_offset}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>
 
    <!-- Chassis of the robot -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
            </geometry>
            <material name="Blue" />
        </visual>  

        <visual>
            <origin xyz="0 ${-support_distance / 2} ${support_zero}" rpy="0 0 0" />
            <geometry>
                <box size="${support_x_size} ${support_y_size} ${support_z_size}" />
            </geometry>
            <material name="Blue" />
        </visual>

        <visual>
            <origin xyz="0 ${support_distance / 2} ${support_zero}" rpy="0 0 0" />
            <geometry>
                <box size="${support_x_size} ${support_y_size} ${support_z_size}" />
            </geometry>
            <material name="Blue" />
        </visual>

        <visual>
            <origin xyz="0 0 ${tray_zero}" rpy="0 0 0" />
            <geometry>
                <box size="${tray_x_size} ${tray_y_size} ${tray_z_size}" />
            </geometry>
            <material name="Blue" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
            </geometry>
        </collision>     

        <inertial>
            <mass value="${base_mass}" />
            <origin xyz="0 0 0" />
            <box_inertia m="${base_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}" /> 
        </inertial>    
    </link>
        
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- Wheels -->
    <wheel lr="left" parent="base_link" translateX="0" translateY="${-wheel_y_offset}" translateZ="${wheel_z_offset}" />
    <wheel lr="right" parent="base_link" translateX="0"  translateY="${wheel_y_offset}" translateZ="${wheel_z_offset}" />

    <!-- Castors -->
    <caster fb="front" parent="base_link" translateX="${caster_front_x_offset}" translateY="0" translateZ="${caster_z_offset}" />
    <caster fb="back" parent="base_link" translateX="${caster_back_x_offset}" translateY="0" translateZ="${caster_z_offset}" />

	<!-- Realsense R200 -->
	<sensor_r200 parent="base_link" r200_cam_y_rotation="${M_PI}" r200_cam_px="${r200_x_offset}" r200_cam_py="${r200_y_offset}" r200_cam_pz="${r200_z_offset}" />

	<!-- Stargazer -->
	<stargazer parent="base_link" translateX="${stargazer_x_offset}" translateY="${stargazer_y_offset}" translateZ="${stargazer_z_offset}" />

  	<joint name="laser_frame_joint" type="fixed">
  	  <origin xyz="${base_x_size/2} 0 0" rpy="0 0 0" />
  	  <parent link="base_footprint" />
  	  <child link="laser_frame" />
  	</joint>
  	<link name="laser_frame" >
      <visual>
       <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
         <sphere radius="0.005"/>
        </geometry>
        <material name="orange">
          <color rgba="0 0 1 1"/>
        </material>
      </visual>
  	</link>
  	
  	<xacro:sick_tim310 name="laser" ros_topic="scan" />

    <!-- Differential drive controller  -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>True</publishWheelTF>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${2*wheel_y_offset}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>srsnode_motion/odometry</odometryFrame> 
            <odometryTopic>srsnode_motion/odometry</odometryTopic> 
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so" />
    </gazebo>

</robot>
